services:
  postgres:
    image: postgres:16
    container_name: popula-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: popula
    ports:
      - "5432:5432"
    volumes:
      - popula-postgres-data:/var/lib/postgresql/data

volumes:
  popula-postgres-data: